apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "chart.fullname" . }}-atlas'
  namespace: {{ .Values.namespace }}
data:
  consumer-topics: {{ .Values.configmap.atlas.consumerTopics }}
  public-server: {{ .Values.configmap.atlas.publicServer }}
  internal-server: {{ .Values.configmap.atlas.internalServer }}
  scribe-topic: {{ .Values.configmap.atlas.scribeTopic }}
  model-name: {{ .Values.configmap.atlas.modelName }}
  model-version: {{ .Values.configmap.atlas.modelVersion }}